# Generated by Django 6.0.4 on 2026-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Software', 'Software'), ('AI', 'AI'), ('Cybersecurity', 'Cybersecurity'), ('Telecommunication', 'Telecommunication'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Ecommerce', 'Ecommerce'), ('Manufacturing', 'Manufacturing'), ('Construction', 'Construction'), ('Logistics', 'Logistics'), ('Marketing', 'Marketing'), ('Consulting', 'Consulting'), ('Restaurant', 'Restaurant'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=100),
        ),
    ]
