# Generated by Django 6.0.4 on 2026-04-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('software', 'Software'), ('ai', 'AI'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('telecom', 'Telecommunication'), ('retail', 'Retail'), ('other', 'Other')], max_length=100),
        ),
    ]
